version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: kunaldevopsmastery/mern-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/loginDB
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    image: kunaldevopsmastery/mern-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_BASE_URL=http://backend:5000
    restart: unless-stopped

volumes:
  mongo-data:
