version: '3.8'

services:
  backend:
    image: kunaldevopsmastery/mern-backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_CONNECT=mongodb+srv://Kunal:Kunal@cluster0.qunea.mongodb.net/Nodejs-Users-Notes?retryWrites=true&w=majority&appName=Cluster0
    restart: unless-stopped

  frontend:
    image: kunaldevopsmastery/mern-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_BASE_URL=http://note-making-proj-alb-1900749472.eu-north-1.elb.amazonaws.com:5000
    restart: unless-stopped

volumes:
  mongo-data:
